### ISSUE TITLE
aws completion broken on macOS

### ISSUE THREAD

**Issue by disrupted** [rsteube/carapace-bin#1056]
macOS with zsh 5.8.1

when invoking the completion for aws I am receiving the following error:

```sh
ERR -- exec: "python": executable file not found in $PATH  _
```

macOS recently removed the deprecated Python 2.7 which it came bundled with. Now `python` is unbound by default.

I also tried symlinking `python3` (Python 3.9 installed through Homebrew) to `python`, then I am receiving

```sh
ERR -- Traceback (most recent call last):  _
```

Please let me know if you need anything else to debug this issue.

**Comment by rsteube** [comment]
The aws completer is currently simply bridging `aws_completer` (as it is quite complex and changes often).
This includes two variants depending how it is installed. The compiled binary is simply invoked but for the python package this [script](https://github.com/rsteube/carapace-bin/blob/master/completers/aws_completer/cmd/complete.py) is executed.
The advantage of the latter is that the `aws_completer` actually has descriptions which [aren't exposed by the binary release](https://github.com/aws/aws-cli/issues/6344).

The first error should occur [here](https://github.com/rsteube/carapace-bin/blob/master/completers/aws_completer/cmd/root.go#L86) where `python` is invoked (should this be `/usr/bin/env python`?).

The second error might indicate that the script isn't working anymore with the current version - will try it out locally.
Btw. the aws_completer does support zsh natively so you might source that after carapace to have sth. working now.

**Comment by rsteube** [comment]
Seems it does not return `Result` anymore. Removed the python variant and fixed environment variables (recent change in carapace).

**Comment by disrupted** [comment]
Thanks for the amazingly quick response. I've updated to the new carapace release and it is working now.
To be honest I didn't quite catch what you mean by 'compiled binary' in regards to the aws cli. I thought they simply distribute a Python script, at least that's what Homebrew installs (`brew install awscli`). I am not aware of a compiled alternative, although I would probably prefer that.

**Comment by rsteube** [comment]
Homebrew probably uses the `pip install` version. I think the ones [here](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) have the python code somehow compiled to a binary. Not sure if it has a performance advantage though.

**Comment by rsteube** [comment]
@disrupted whops - i think the issue might actually be that pip and homebrew install the old v1 by default.
So the python script might actually still be working, only just for the new v2 (the default branch on github is still v1, which was a bit misleading).

**Comment by disrupted** [comment]
ah, that's good to know. In this case I am gonna try installing the new v2.

**Comment by disrupted** [comment]
I double-checked and the default is already v2 on Homebrew so I think we should be fine

```
❯ brew info awscli
awscli: stable 2.5.8 (bottled), HEAD
Official Amazon AWS command-line interface
https://aws.amazon.com/cli/
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/awscli.rb
License: Apache-2.0
==> Dependencies
Build: cmake ✔, rust ✘
Required: python@3.9 ✔, six ✔
==> Options
--HEAD
        Install HEAD version
```
