### ISSUE TITLE
Documentation for spec files?

### ISSUE THREAD

**Issue by iandol** [rsteube/carapace-bin#1084]
In general spec files are fairly straight-forwards to understand, but I was wondering exactly what `pos1` and `pos2` do in the example yaml you show?

```yaml
  positional:
  -  ["pos1", "pos2"]
  -  ["$_files"]
```

**Comment by rsteube** [comment]
Yes, i'm going to add documentation for that - things are still fresh and i am still figuring out some parts.
Naming them `pos1` and `pos2` is a quite misleading, it's just the possible values for position1:

```sh
example --flag flagValue pos1 pos2 pos3
```

```yaml
positional:
  - ["a", "b", "c"] # pos1
  - ["$files"] # pos2
positionalany: ["1", "2", "3"] # pos3
```

Values itself are either static or `macros` which can return more than one value like `$files` (i am removing the underscore in the next version and use it for custom macros).
Then there are modifier macros like `$list(.)` (make everything a `.` separated  list of unique values) and `$nospace` (don't add space suffix).
I'm going to expose the actions of carapace-bin (#1083) so things like `["$_tools.docker.Containers"]` will be possible.

**Comment by rsteube** [comment]
related https://github.com/rsteube/carapace-spec/issues/19

**Comment by rsteube** [comment]
https://rsteube.github.io/carapace-spec/carapace-spec.html
https://rsteube.github.io/carapace-bin/specs.html
