### ISSUE TITLE
Improve TMUX completer?

### ISSUE THREAD

**Issue by iandol** [rsteube/carapace-bin#1104]
`tmux` has a large number of commands:

https://man.openbsd.org/tmux#COMMANDS

Currently `carapace` only completes the small number of flags, and it would be great to get the main commands to complete (they do at least in `zsh`). I do realise it is a complex command to support!

**Comment by rsteube** [comment]
Yeah, i realized that after i had that one done. Was planning to finish it up, but i am not using `tmux` myself so it was hard to determine which the main commands even are (i think the documentation wasn't so great or at least quite complex).

related: https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_tmux
related: https://tmuxguide.readthedocs.io/en/latest/tmux/tmux.html

**Comment by iandol** [comment]
Yikes, yes that looks right, I imagine most people only use a few of these at the command line to be honest...

**Comment by iandol** [comment]
Note fish only supports completion of "Clients and Sessions" commands, not "Windows and Panes" commands, this is a fair shortcut I think as the most used commands are for sessions from terminal...

https://github.com/fish-shell/fish-shell/blob/master/share/completions/tmux.fish

**Comment by rsteube** [comment]
tracking in #1108
