### ISSUE TITLE
What is ${UserConfigDir} in 0.12.1?

### ISSUE THREAD

**Issue by iandol** [rsteube/carapace-bin#1105]
This is probably a dumb issue. I wanted to link some spec files so that carapace will auto-load them, and I assumed `${UserConfigDir}` was going to be $E:XDG_CONFIG_HOME which is `~/.config` at least on my machine. So I soft linked two yaml files into `~/.config/carapace/specs/` but on restarting elvish I do not get those completions. The files are named after the commands, e.g. `pandocomatic.yaml` as the release notes specified.

**Comment by rsteube** [comment]
Should be correct, did you start a new shell?

**Comment by rsteube** [comment]
[UserConfigDir](https://pkg.go.dev/os@go1.18.1#UserConfigDir)

> On Unix systems, it returns $XDG_CONFIG_HOME as specified by https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html if non-empty, else $HOME/.config. On Darwin, it returns $HOME/Library/Application Support. On Windows, it returns %AppData%. On Plan 9, it returns $home/lib.

`$HOME/Library/Application Support/carapace/specs` maybe?

**Comment by iandol** [comment]
OK, so I've moved my soft links into that folder:

```
Diogenes » ~ 
ⓔ ▶︎ ls -al '/Users/ian/Library/Application Support/carapace/specs'
total 0
drwxr-xr-x  4 ian  staff   128B  9 May 21:29 ./
drwxr-xr-x  3 ian  staff    96B  8 May 13:03 ../
lrwxr-xr-x  1 ian  staff    50B  9 May 21:29 pandocomatic.yaml@ -> /Users/ian/.dotfiles/completions/pandocomatic.yaml
lrwxr-xr-x  1 ian  staff    49B  9 May 21:29 scrivomatic.yaml@ -> /Users/ian/.dotfiles/completions/scrivomatic.yaml
```

And verified that is what carapace thinks it is using:

```
Diogenes » ~ 
ⓔ ▶︎ carapace --help
multi-shell multi-command argument completer

…

  Shell parameter is optional and if left out carapace will try to detect it by parent process name.
  Some completions are cached at [/Users/ian/Library/Caches/carapace].
  Config is written to [/Users/ian/Library/Application Support/carapace]. 
…
```

Then restart my terminal but no completion:

```
error: no candidates

Diogenes » ~ 
ⓔ ▶︎ scrivomatic -[tab]
```

**Comment by iandol** [comment]
OK the problem appears to be the soft links:

```
ⓔ ▶︎ eval (carapace --spec '/Users/ian/Library/Application Support/carapace/specs/scrivomatic.yaml' | slurp)

error: no candidates

Diogenes » ~ 
ⓔ ▶︎ scrivomatic -
```

But if I use the source file directly:

```
Diogenes » ~ 
ⓔ ▶︎ eval (carapace --spec /Users/ian/.dotfiles/completions/scrivomatic.yaml | slurp)
                                                                                         
Diogenes » ~ 
ⓔ ▶︎ scrivomatic --build 
 COMPLETING argument  
--build (For LaTeX output, run latexmk)                 
--buildclean (For LaTeX output, run latexmk and cleanup)
...
``` 

As I use git to version all my config files I use soft links to put them in the correct places. Can this be made to work with soft links?

**Comment by rsteube** [comment]
No, i think it's the space in the unquoted path :see_no_evil:

**Comment by iandol** [comment]
Hi, I updated to 0.12.2 which I think contains #1113 but I still see the same behaviour:

```
Diogenes » ~ 
ⓔ ▶︎ eval (carapace --spec '/Users/ian/Library/Application Support/carapace/specs/scrivomatic.yaml' | slurp)
error: no candidates

Diogenes » ~ 
ⓔ ▶︎ scrivomatic -
```

**Comment by rsteube** [comment]
whats the output of `carapace _carapace`? just the line with the spec path

**Comment by iandol** [comment]
```
put pandocomatic scrivomatic | each {|c|
    set edit:completion:arg-completer[$c] = {|@arg|
        set edit:completion:arg-completer[$c] = {|@arg| }
        eval (carapace --spec "/Users/ian/Library/Application Support/carapace/specs/"$c".yaml" elvish | slurp)
        $edit:completion:arg-completer[$c] $@arg
    }
  
}
```

Look ok to me?

```
Diogenes » ~ 
ⓔ ▶︎ var c = "scrivomatic"
                                                                                                                                                                   
Diogenes » ~ 
ⓔ ▶︎ ls -al "/Users/ian/Library/Application Support/carapace/specs/"$c".yaml"
lrwxr-xr-x  1 ian  staff    49B  9 May 21:29 /Users/ian/Library/Application Support/carapace/specs/scrivomatic.yaml@ -> /Users/ian/.dotfiles/completions/scrivomatic.yaml
```

**Comment by rsteube** [comment]
ah, forgot about the script generated by `carapace --spec "/tmp/Application Support/.config/carapace/specs/"$c".yaml" elvish`

**Comment by iandol** [comment]
OK, this seems to have fixed it, thanks!!!
