### ISSUE TITLE
nushell: don’t override builtins

### ISSUE THREAD

**Issue by flying-sheep** [rsteube/carapace-bin#1213]
In nushell, commands like `env` or `ls` are builtins.

Redefining them as “extern” makes them behave differently.

`_carapace` should only override commands that aren’t built into newshell.

**Comment by rsteube** [comment]
Thanks for pointing this out. I am aware of this but haven't pushed for a fix yet as https://github.com/rsteube/carapace/issues/499 is still needed for decent nushell support.
I was planning to add a configuration mechanism similar to the style one at some point where this and cache times can be configured.
Don't mind hardcoding the exclusion though for the moment for a quick fix.
