### ISSUE TITLE
turn off argument completion

### ISSUE THREAD

**Issue by geekscrapy** [rsteube/carapace-bin#1219]
Firstly, great tool!

Hi, How can I turn off argument completion? I would prefer filenames/directories to be shown instead.
<img width="563" alt="image" src="https://user-images.githubusercontent.com/11225502/177330735-ad1854ba-3bf6-4971-9418-2118bc78aebf.png">

Second question:
I loose some key bindings when I invoke ble.sh. For example I am on a mac (with iterm) and use ALT+DELETE to delete a previous word. This is disabled when I use ble.sh

**Comment by rsteube** [comment]
Flags should only be completed when the current word starts with `-`. As i understand you are using `ble.sh` - i had some issues with it overriding the completion on the first `[TAB]`. The completions in the screenshot are not the ones from `carapace`.
Don't know about the `ALT-DELETE` issue (which is related to `ble.sh`) as i am using [elvish](https://elv.sh/) myself - maybe @akinomyoga can help.

**Comment by akinomyoga** [comment]
## Re: Filename completions

> Hi, How can I turn off argument completion? I would prefer filenames/directories to be shown instead.

@geekscrapy `ble.sh` combined with `bash-completion` by default is supposed to generate filenames and directory names for the empty-word completion. The behavior of the picture seems to be different from the default behavior of `ble.sh`. I would like to know the detailed setup in your environment.

- Which version of ble.sh do you use? If you are using ble-0.3, could you instead try ble-0.4? If you are not using the latest version of ble-0.4, could you update it to the latest master by running `ble-update`?
- What would be shown by pressing [Ctrl+X][Ctrl+V] in a `ble.sh` session?

## Re: ALT-DELETE in iTerm2

@geekscrapy It depends on the detailed terminal settings about what key sequences the terminal sends for ALT-DELETE. To check the sequence for the present setting, could you tell what would be shown after pressing `[Ctrl+V][ALT+DELETE]` in a `ble.sh` session?

```bash
$ echo [press Ctrl+V][press ALT+DELETE]     <-- Q. What will be shown?
```

Also, I'm interested in what would be sent by pressing `[Ctrl+V][DELETE]`

```bash
$ echo [press Ctrl+V][press DELETE]     <-- What will be shown?
```

Also, you might also want to check the description of ALT in iTerm2 under the item "*M-right does not work in my terminal*" on [the Q&A page](https://github.com/akinomyoga/ble.sh/wiki/Q&A).

**Comment by akinomyoga** [comment]
### Re: Issues with ble.sh  on the first `[TAB]`

> i had some issues with it overriding the completion on the first `[TAB]`.

@rsteube Maybe I can try it later when I have time. If there are certain conditions to reproduce it, I'd appreciate it if you could provide the details.

**Comment by rsteube** [comment]
@akinomyoga added ble to the Dockerfile: https://github.com/rsteube/carapace/pull/538 .
Seems to work alright now.

**Comment by akinomyoga** [comment]
@rsteube Thanks! I've tried `docker-compose run --rm ble`, where the completion seems to work fine!

**Comment by akinomyoga** [comment]
Hmm, I guess

```diff
 _carapace_lazy() {
   source <(carapace $1 bash-ble)
-   $"_$1_completion"
+  "_$1_completion_ble" "$@"
 }
 complete -F _carapace_lazy acpi
```

By the way, I'm not sure if `carapace` targets Bash 3.2 also, but Bash 3.2 does not support sourcing from pipes, i.e., `source <(cmd)` doesn't work. Instead, `eval -- "$(cmd)"` is the option that always works.

```diff
 _carapace_lazy() {
-  source <(carapace $1 bash-ble)
+  eval -- "$(carapace "$1" bash-ble)" &&
   "_$1_completion_ble" "$@"
 }
 complete -F _carapace_lazy acpi
```

**Comment by rsteube** [comment]
Nah, i'm just blind. It's supposed to be:
```diff
-   $"_$1_completion"
+   $"_$1_completion_ble"
```

I'm generally targeting fairly recent versions at the moment. So unless someone *really* needs it i would stick to that.

**Comment by akinomyoga** [comment]
Thanks for the fix!

> I'm generally targeting fairly recent versions at the moment. So unless someone _really_ needs it i would stick to that.

OK!

**Comment by rsteube** [comment]
@geekscrapy did you get it working?

**Comment by geekscrapy** [comment]
Hi! I'll be able to try it again after the weekend.
RE Q1 @akinomyoga , this was the first time I used ble.sh so I presume it would be up-to-date. I'll check though

(did my original issue get moved from the ble.sh issue list? I'd never heard of carapace before seeing this thread?  Or maybe I was overtired 🙃)

**Comment by akinomyoga** [comment]
> (did my original issue get moved from the ble.sh issue list? I'd never heard of carapace before seeing this thread? Or maybe I was overtired 🙃)

Oh, does it mean you intended to create an issue in `ble.sh`? This issue was created here from the beginning and has never been moved since then. Maybe you have been opening multiple tabs in the web browser, picked up the wrong one, and created this issue? That might be possible if you have found `ble.sh` in a page where both ble.sh and carapace are mentioned, such as https://github.com/oilshell/oil/issues/915.

I guess we want to move the issue to `ble.sh` if possible, but I think it's not possible because there is no user who has the owner privilege or the write access to both repositories.

**Comment by rsteube** [comment]
Probably best to just reopen a new one there.
