### ISSUE TITLE
Tilde+tab triggers backslash

### ISSUE THREAD

**Issue by LangLangBart** [rsteube/carapace-bin#1277]
### description
Pressing the `tab` key after the `~` (tilde)  symbol adds a `\` (backslash) in front of the tilde symbol
- macOS
  - default terminal 
- zsh setup
  - romkatv/zsh4humans

### to reproduce
1. Type `mv ~/`
2. Press the `tab` key 
3. a backslash appears before the tilde symbol
4. see GIF below for more clarity

#### GIF
![issue](https://user-images.githubusercontent.com/92653266/187018572-8e92cc4e-0424-4104-b821-cb3fed49a7aa.gif)

PS: Found out about this repo from a post in the [cli/cli](https://github.com/cli/cli/issues/360#issuecomment-689615594) repo. Besides the `~` (tilde)  issue very happy with it.

**Comment by rsteube** [comment]
Yes, this is done by [compadd](https://zsh.sourceforge.io/Doc/Release/Completion-Widgets.html#Completion-Builtin-Commands) which currently handles quoting (https://github.com/rsteube/carapace/issues/313) and related to how zsh does file expansion.
I think there was a zsh config that expands the path before passing it to a command which would be a quick fix, can't find it at the moment though.

This is actually a bit tricky (as there can also be files/folders/arguments with a `~` prefix) and I've been avoiding the issue so far to first get a better understanding of how to handle it.
I have general idea now though and will have a look at it.

**Comment by LangLangBart** [comment]
```zsh
❯ carapace --version
0.15.0
```

I can confirm that the `\` (backslash) no longer appears, but it adds a space after the selected word. 
![them](https://user-images.githubusercontent.com/92653266/187088237-de9ca4d6-3458-4ea3-9a7e-8d80524ddbbe.gif)

**Comment by rsteube** [comment]
Hmm..this is somehow related to the fzf plugin :thinking: . It works with the standard zsh menu.

**Comment by rsteube** [comment]
Either related to a `fzf-tab`  or `zsh4humans` configuration. Issue doesn't seem to appear using `fzf-tab` directly.

**Comment by rsteube** [comment]
Ah, thought it uses [fzf-tab](https://github.com/Aloxaf/fzf-tab) but looks like a custom script: https://github.com/romkatv/zsh4humans/blob/ced34c2bc8432be535acf0e513e17edfcf240ee3/fn/z4h-fzf-complete
