### ISSUE TITLE
Windows release

### ISSUE THREAD

**Issue by jmoore34** [rsteube/carapace-bin#1378]
Is there Windows support? If so, are there plans to release Windows binaries?

**Comment by rsteube** [comment]
There already are windows binaries in the releases, you just have to expand the assets on the page.
It is also published to a [scoop](https://scoop.sh/) repo (see [docs](https://rsteube.github.io/carapace-bin/installation.html#scoop)).

Current limitations though as the completers currently mostly target linux (which i use):
- releases contain all completers even if not applicable to windows (#1326)
- actions need to be adapted for various environments (so some completions might not work for windows yet - e.g. checking the wrong files/service)
- custom executed commands in spec using powershell (should be fixed now with https://github.com/rsteube/carapace-spec/issues/16 but i think there are still some issues with line ending)

**Comment by Araxeus** [comment]
Would be nice to have it on https://github.com/microsoft/winget-pkgs/issues/99770

**Comment by Araxeus** [comment]
I've submitted a PR to winget pkgs: https://github.com/microsoft/winget-pkgs/pull/100761
