### ISSUE TITLE
mpv error

### ISSUE THREAD

**Issue by iandol** [rsteube/carapace-bin#1417]
Trying to use `mpv` using a hardware decoder, I get this error:

```
▶︎ mpv --hwdec=vdpau CoERR
 COMPLETING argument  
ERR (unknown flag: --hwdec)  _
```

In general, it would be good that **if** the completer cannot find a flag, it should fallback to completing the file path anyway as the error is very disruptive. I tried to use `--` to stop parsing but this also doesn't work; the solution is remove the flag, then complete the path, then re-add the flag which wastes a lot of time... Thanks as always!

**Comment by rsteube** [comment]
Having file completion fallback has a lot of other problems (like not knowing if a flag takes a value or not) so i'm still quite strong on the current solution.
Getting an error also helps identifying that something is actually missing, could think of an environment variable or config though the allows to temparily skip it until the command gets fixed.

Seems i had not finished it up yet, there's a massive amount of flags in `mpv` :open_mouth: .
Added them with a little sed magic but the descriptions are still missing and a lot of flags have no completion yet.

**Comment by iandol** [comment]
OK, thanks as always for a great tool. I understand why you want to surface errors, though least in this example the flag was given a value `--hwdev=vdpau` and so at least here a fallback might make sense? A temporary ENV override would be great if feasible.
