### ISSUE TITLE
Argcomplete bridge does not autocomplete when positional arguments is partially typed

### ISSUE THREAD

**Issue by vyvl** [rsteube/carapace-bin#1486]
**Describe the bug**
Argcomplete bridge works fine to complete positional arguments when no prefix of the argument is present in the commandline. If you enter a prefix and try to autocomplete it, it may fail

**To Reproduce**
1. Install pipx - https://pypa.github.io/pipx/
2. Add the below spec to carapace
```
name: pipx
completion:
  positionalany: ["$_bridge.Argcomplete(pipx)"]
```
3. Try to invoke autocompletion by `pipx ensur<TAB>`
4. No autocompletion

**Expected behavior**
It should complete to `pipx ensurepath`

**Screenshots**
It shows ensurepath argument as long as I don't type anything, or only first two characters. If I type more it does not autocomplete
![image](https://user-images.githubusercontent.com/8201617/213690771-9d45ea0a-ccfd-466c-84f5-896ddf2db220.png)
![image](https://user-images.githubusercontent.com/8201617/213691178-575549dd-f9fe-4bce-9783-7539b98f711b.png)
![image](https://user-images.githubusercontent.com/8201617/213690950-2f7b7964-072b-425b-9a36-35a790347d94.png)

**OS (please complete the following information):**
 - [ ] Linux
 - [x] OSX
 - [ ] Windows

**Shell (please complete the following information):**
 - [ ] Bash
 - [ ] Elvish
 - [ ] Fish
 - [x] Nushell
 - [ ] Oil
 - [ ] Powershell
 - [ ] Xonsh
 - [x] Zsh

**Additional context**
The behavior is not unique for `pipx` , I initially faced this in one of our internal tools in my job, then tried to reproduce with pipx. So it should be happening for anything that uses argcomplete

**Comment by rsteube** [comment]
Seems to me that argcomplete doesn't like partial words to be completed and it needs to be left out.
Did this for flags already but had not noticed it is needed for positional arguments as well.

**Comment by vyvl** [comment]
That was swift, thank you
