### ISSUE TITLE
configuring the style of the completion list could be better documented

### ISSUE THREAD

**Issue by krader1961** [rsteube/carapace-bin#1565]
### Request

I installed Carapace support for Elvish and love it but for one detail: the default completion list style is hard to read on a terminal with a light background. I've tentatively settled on running these commands:

```
carapace --style 'carapace.Value=magenta'
carapace --style 'carapace.Description=italic'
```

It would help users of this great tool if the available options for changing the style of the completion list was better documented.

**Comment by rsteube** [comment]
Regarding the available style options or the core configurations (value/description)?
I've got a short example here but i can add some more content to it: https://rsteube.github.io/carapace-bin/style.html#value

Btw. might be good idea to detect light background and have a different default for it :thinking:
