### ISSUE TITLE
Homebrew tap not updating

### ISSUE THREAD

**Issue by iandol** [rsteube/carapace-bin#1638]
### Request

Hi, the homebrew tap (and I asume Scoop bin) have not been updated for several weeks, so I am still using V0.23. I can manually install of course but prefer to use homebrew on my Linux and macOS machines. Thanks!

**Comment by iandol** [comment]
Oh, I am an idiot, I see the official release is still V0.23, I got confused with carapace releases I think...

**Comment by rsteube** [comment]
Sorry about that :grin: . I've been moving things around and ended up doing a couple for releases in the other projects.
