### ISSUE TITLE
nushell init is not an idiomatic integration

### ISSUE THREAD

**Issue by aserowy** [rsteube/carapace-bin#1692]
### Request

The current implementation given by 'command _carapace nushell' prevents two things:

1. the path initialization is not usable cross platform:

``` go
func pathSnippet(shell string) (snippet string) {
[...]
	case "nushell":
		snippet = fmt.Sprintf(`let-env PATH = ($env.PATH | prepend "%v")`, binDir)
```
PATH is not present in Windows. Beyond that every pkg-Manager should install carapace in an already added location. Thus, the let-env should not be neccesary.

2. current implementation overwrites a set config:

In nushell you want to init the config every time, starting nu. E.g. for starship you call the following in env.nu
``` nu
mkdir ~/.cache/starship
starship init nu | save --force ~/.cache/starship/init.nu
```
and source the given file in config.nu with
``` nu
source ~/.cache/starship/init.nu
```
The generated script creates a direct reset, which prevents this method.

### Proposed solution

1. Remove the path init
2. Rewrite the init method and suggested help

### Anything else?

Heho,

i wrote the proposed solution somewhat short. I would love to pr the changes, if you want. Just let me know!

TYVM!!!!1 for this awesome tool! (I cant stress this enough how cool a carapace + starship is to be able to configure every shell in a heartbeat :D <3)

Kind regards
Alexander

**Comment by rsteube** [comment]
1. PATH isn't updated for where `carapace` but the [shim](https://rsteube.github.io/carapace-bin/spec/shim.html) folder which is a bit of trickery to support runnable specs (cross shell alias / custom nested commands)

2. The script for nushell is currently just an example/hint of how to update the nushell config as there is no eval/source of commmand output. Adopting the starship way could be nice, but there's the issue with how external completers are registered and users wanting to customize that.

Open for improvements/pr here but i don't have access to a computer for a while so i can't really look at it for now.

**Comment by aserowy** [comment]
Heho,

ty for the feedback. Ill tinker something in the next couple days.

Regards
Alexander

**Comment by aserowy** [comment]
ok, was not that big... :D

**Comment by tminich** [comment]
@aserowy Does this deal with Windows using backslashes? I had the issue that the path override in the generated file uses a mixture of unescaped backslashes and forward slashes leading to an invalid config file. My current workaround is to generate the `.nu` file (starship-style) with
```sh
carapace _carapace | str replace '\\' '/' -a | str replace 'PATH' 'Path' -a | str replace 'config' 'carapace_config' | $in + "\nlet-env config = ($env.config | upsert completions $env.carapace_config.completions)"  | save -f ~/.cache/carapace.nu
```

**Comment by aserowy** [comment]
good question. Im on nixos right now. I'll check the generated path tomorrow. (working on windows/wsl)

**Comment by rsteube** [comment]
Yes, there was an issue with backslashes somewhere. Think this was due the build on windows so i didn't notice it before (which breaks it). Should all be forward slash.

I should be back in a couple of weeks (5-8), can have a look at all this then.

**Comment by aserowy** [comment]
@tminich 
Heho,

i looked into it and the path comes from 'configDir, err := xdg.UserConfigDir()' currently. If the implementation from xdg resolves a wrong path string, this should be tracked in a separate issue. I would not add the fix as capability into the nu init.

On the other hand, we could add these paths with $env.HOME and the windows counter parts. Thus, we would only reuse the configdir path and let nu handle the rest.

@rsteube 
How do you think about it?

**Comment by tminich** [comment]
The content itself is technically not wrong, windows is fine with a mixture of \ and /, but the backslashes need to be escaped when written out as string content into a .nu file.

**Comment by aserowy** [comment]
ah, ok! got it :D

In that case, ill add this into the function.

**Comment by aserowy** [comment]
@tminich 
I added the fixed replaces with in the pr. Thus, the output would generate e.g. C:\\Users\\serowy\\AppData\\Roaming/carapace/bin
Would this fit your solution?

**Comment by tminich** [comment]
That should work. Personally I'm indifferent, but maybe it would be cleaner to convert them all to forward slashes so it's consistent.
I'd say it's @rsteube 's call.

**Comment by rsteube** [comment]
> ok, was not that big... :D
> 
> PS: plz, do not feel stressed. Take your time! Btw. can you give me a hint, where i should rework the docs?

instructions in https://github.com/rsteube/carapace-bin/blob/master/README.md and https://github.com/rsteube/carapace-bin/blob/master/docs/src/setup.md

**Comment by rsteube** [comment]
> That should work. Personally I'm indifferent, but maybe it would be cleaner to convert them all to forward slashes so it's consistent. I'd say it's @rsteube 's call.

I'm all for forward slashes unless it really doesn't work. (AFAIK all the supported shell can handle that)

**Comment by aserowy** [comment]
Ill add those and the merged integration into scoop extras (Installer for win) into the next pr
