### ISSUE TITLE
`paru` and `yay`

### ISSUE THREAD

**Issue by zacharyburnett** [rsteube/carapace-bin#1696]
### Request

[`paru`](https://github.com/Morganamilo/paru) and [`yay`](https://github.com/Jguer/yay) are wrappers around `pacman` that extend functionality and query the AUR. 

### Proposed solution

Both wrappers support the majority of `pacman`s arguments, so I assume that implementing the completers would overlap a lot of completions from `pacman`. Is there a way to "import" those from `pacman` into the new completer to reduce duplication of code? (I don't know much about Go, sorry!)

**Comment by rsteube** [comment]
If it's a full (sub)command it can be embedded: https://rsteube.github.io/carapace-bin/spec/bridge.html#carapacebin

Otherwise it needs to be done again, but actions like package search can be reused.

Think these abuse flags as subcommands like pacman (e.g. `-Syu`) that requires some trickery.
