### ISSUE TITLE
(Package request) Zoxide

### ISSUE THREAD

**Issue by cbr9** [rsteube/carapace-bin#1892]
### Request

Hello,

Would it be possible to add [zoxide](https://github.com/ajeetdsouza/zoxide) completion, querying the local zoxide database?

**Comment by rsteube** [comment]
Maybe. There were some issues where the inserted value needs to match the already present prefix on the command line.
Bash has been pretty picky on this, but I think I've got the wordbreaks now working well enough for this to not be a problem.
Having different display values than what would have to be typed is also normally not a good idea as Bash has no menu completion where you can cycle through (so you don't know what to type).

Think I had a look at zoxide in the past where some of this was an issue, but it could be fine now.
