### ISSUE TITLE
git checkout: can't autocomplete file path in nushell

### ISSUE THREAD

**Issue by WindSoilder** [rsteube/carapace-bin#1894]
### Current Behavior

As title, I have a file called a.txt, and I change the file's content, then I type `git checkout ./a<tab>`, it shows that "NO RECORDS FOUND"

### Expected Behavior

I'd expect it shows a.txt

### Version

0.27.0

### OS

- [ ] Linux
- [X] OSX
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [X] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

### Anything else?

It seems that it's similar to #1617, and `git reset` also has the same issue

**Comment by rsteube** [comment]
Hmm..can't reproduce this :thinking:. With the `./`  prefix it's just the standard file completion like `bat <TAB>`.
I've created a file named `a.txt` and it is completing it - am I missing sth.?

**Comment by WindSoilder** [comment]
Oh, I'm sorry for my wrong description, it's not `git blame`, which is fixed before.

They are `git reset` and `git checkout`, can you reproduce them?

**Comment by rsteube** [comment]
Ah yes, I can.
Seems I had file completion at least for the dash arguments: https://github.com/rsteube/carapace-bin/blob/master/completers/git_completer/cmd/reset.go#L45
But that is from before I added decent support for dash argument completion so this has no effect now and needs to be changed.

Git has a lot of variants in the commands so often it's not very clear how to complete some arguments (or I have to make some opiniated choices). But this one is easy to fix.

**Comment by rsteube** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Reset-Demystified
