### ISSUE TITLE
jj

### ISSUE THREAD

**Issue by rsteube** [rsteube/carapace-bin#1970]
- [x] abandon    Abandon a revision
- [x] backout    Apply the reverse of a revision on top of another revision
- [x] branch     Manage branches
  - [x] create   Create a new branch [aliases: c]
  - [x] delete   Delete an existing branch and propagate the deletion to remotes on the next push [aliases: d]
  - [x] forget   Forget everything about a branch, including its local and remote targets [aliases: f]
  - [x] list     List branches and their targets [aliases: l]
  - [x] set      Update a given branch to point to a certain commit [aliases: s]
  - [x] track    Start tracking given remote branches
  - [x] untrack  Stop tracking given remote branches
  - [x] help     Print this message or the help of the given subcommand(s)
- [x] cat        Print contents of a file in a revision
- [x] checkout   Create a new, empty change and edit it in the working copy [aliases: co]
- [x] chmod      Sets or removes the executable bit for paths in the repo
- [x] commit     Update the description and create a new change on top [aliases: ci]
- [x] config     Manage config options
  - [x] list  List variables set in config file, along with their values [aliases: l]
  - [x] get   Get the value of a given config option. [aliases: g]
  - [x] set   Update config file to set the given option to a given value [aliases: s]
  - [x] edit  Start an editor on a jj config file [aliases: e]
  - [x] help  Print this message or the help of the given subcommand(s)
- [x] describe   Update the change description or other metadata [aliases: desc]
- [x] diff       
- [x] diffedit   Touch up the content changes in a revision with a diff editor
- [x] duplicate  Create a new change with the same content as an existing one
- [x] edit       Edit a commit in the working copy
- [x] files      List files in a revision
- [x] git        Commands for working with the underlying Git repo
  - [x]  remote  Manage Git remotes
    - [x] add     Add a Git remote
    - [x] remove  Remove a Git remote and forget its branches
    - [x] rename  Rename a Git remote
    - [x] list    List Git remotes
    - [x] help    Print this message or the help of the given subcommand(s)
  - [x]  fetch   Fetch from a Git remote
  - [x]  clone   Create a new repo backed by a clone of a Git repo
  - [x]  push    Push to a Git remote
  - [x]  import  Update repo with changes made in the underlying Git repo
  - [x]  export  Update the underlying Git repo with changes made in the repo
  - [x]  help    Print this message or the help of the given subcommand(s)
- [x] init       Create a new repo in the given directory
- [x] interdiff  Compare the changes of two commits
- [x] log        Show commit history
- [x] merge      Merge work from multiple branches
- [x] move       Move changes from one revision into another
- [x] new        Create a new, empty change and edit it in the working copy
- [x] next       Move the current working copy commit to the next child revision in the repository.
- [x] obslog     Show how a change has evolved
- [x] operation  Commands for working with the operation log [aliases: op]
  - [x] log      Show the operation log
  - [x] undo     Create a new operation that undoes an earlier operation
  - [x] restore  Create a new operation that restores the repo to an earlier state
  - [x] help     Print this message or the help of the given subcommand(s)
- [x] prev       Move the working copy commit to the parent of the current revision.
- [x] rebase     Move revisions to different parent(s)
- [x] resolve    Resolve a conflicted file with an external merge tool
- [x] restore    Restore paths from another revision
- [x] show       Show commit description and changes in a revision
- [x] sparse     Manage which paths from the working-copy commit are present in the working copy
  - [x] list  List the patterns that are currently present in the working copy
  - [x] set   Update the patterns that are present in the working copy
  - [x] help  Print this message or the help of the given subcommand(s)
- [x] split      Split a revision in two
- [x] squash     Move changes from a revision into its parent [aliases: amend]
- [x] status     Show high-level repo status [aliases: st]
- [x] util       Infrequently used commands such as for generating shell completions
  - [x] completion     Print a command-line-completion script
  - [x] mangen         Print a ROFF (manpage)
  - [x] config-schema  Print the JSON schema for the jj TOML config format
  - [x] help           Print this message or the help of the given subcommand(s)
- [x] undo       Undo an operation (shortcut for `jj op undo`)
- [x] unsquash   Move changes from a revision's parent into the revision [aliases: unamend]
- [x] untrack    Stop tracking specified paths in the working copy
- [x] version    Display version information
- [x] workspace  Commands for working with workspaces
  - [x] add           Add a workspace
  - [x] forget        Stop tracking a workspace's working-copy commit in the repo
  - [x] list          List workspaces
  - [x] root          Show the current workspace root directory
  - [x] update-stale  Update a workspace that has become stale
  - [x] help          Print this message or the help of the given subcommand(s)
- [x] help       Print this message or the help of the given subcommand(s)

---
- [x] tag support: https://github.com/martinvonz/jj/issues/2473 (works with `--revisions "tags()"`)
- [x] full revset support: https://martinvonz.github.io/jj/v0.11.0/revsets/ (just basic support for now)

**Comment by rsteube** [comment]
related #99

**Comment by rsteube** [comment]
fyi @martinvonz

**Comment by martinvonz** [comment]
Wow, that was quick! @BatmanAoD linked to this issue a few days ago (from https://github.com/martinvonz/jj/discussions/2497). Then I think you had barely started, and now it's already done. Thank you!

**Comment by BatmanAoD** [comment]
One issue: when auto-completing branch names, if `<branch>@<upstream>` (e.g. `foo@origin`) is out of sync with the local `<branch>`, the `(ahead by N commits, behind by N commits)` text appears as part of the completion.
