### ISSUE TITLE
git: sort merge completions

### ISSUE THREAD

**Issue by Lillecarl** [rsteube/carapace-bin#2030]
### Current Behavior

https://asciinema.org/a/lWKBOaoTasFAHWr4M4ppMmw7y

When typing git merge and pressing tab I get a list of random commit hashes, HEAD~N and others.

### Expected Behavior

I'd expect it to suggest branches to me, because that's what people merge the most :smi

### Steps To Reproduce

Go into a git repo and type git merge

### Version

930f5585db881fc8ba894fd57e854bbb80bd34da

### OS

- [X] Linux
- [ ] OSX
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [X] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

**Comment by rsteube** [comment]
HEAD commits indeed make no sense here.
The commit hashes aren't random though, but the 100 most recent ones.
With the support for [relative refs](https://rsteube.github.io/carapace-bin/changelog/v0.28.html#git) these are less relevant now.
