### ISSUE TITLE
setup: open /Users/xxx/Library/Application Support/carapace/specs: no such file or directory

### ISSUE THREAD

**Issue by PaulXu-cn** [rsteube/carapace-bin#2240]
### Current Behavior

Install from [rsteube/homebrew-tap](https://github.com/rsteube/homebrew-tap)

```
brew tap rsteube/homebrew-tap
brew install rsteube/tap/carapace
```

and setup [Zsh](https://rsteube.github.io/carapace-bin/setup.html#zsh)
```
# ~/.zshrc
export CARAPACE_BRIDGES='zsh,fish,bash,inshellisense' # optional
zstyle ':completion:*' format $'\e[2;37mCompleting %d\e[m'
source <(carapace _carapace)
```

exec shell
```
source ~/.zshrc
```
show
```
open /Users/xxx/Library/Application Support/carapace/specs: no such file or directory
```

### Version

0.30.1

### OS

- [ ] Linux
- [X] OSX
- [ ] Windows

### Shell

- [ ] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [X] Zsh

**Comment by rsteube** [comment]
The application just looks for [user specs](https://rsteube.github.io/carapace-bin/spec/user.html) when executing `carapace _carapace`.
It's just that the directory did not exists at that point, which isn't really an issue.
