### ISSUE TITLE
bash: menu-complete is adding description to completion

### ISSUE THREAD

**Issue by Mikilio** [rsteube/carapace-bin#2247]
### Current Behavior

If I type `git commi` and use my shortcut for menu-complete, it completes properly the first time. But when repeatedly using it to cycle through the options, it adds the descriptions as well.

### Expected Behavior

When cycling using menu-complete or menu-complete-backward it should complete using only the completion not the description.

### Steps To Reproduce

1. configure readline (.inputrc) to have a button activating menu-complete, eg. (`"\C-i": menu-complete`)
2. use it to complete `git commi`

### Version

0.30.1

### OS

- [X] Linux
- [ ] OSX
- [ ] Windows

### Shell

- [X] Bash
- [ ] Elvish
- [ ] Fish
- [ ] Nushell
- [ ] Oil
- [ ] Powershell
- [ ] Xonsh
- [ ] Zsh

**Comment by rsteube** [comment]
Urgs - I was hoping no one is using the weird stuff.
Can be done, but I need a way to detect if current mode is `complete` or `menu-complete`.

**Comment by Mikilio** [comment]
[Stackoverflow](https://stackoverflow.com/a/6151256) had something promising.

Apparently COMP_TYPE is set differently depending on the operation used.
